// <auto-generated />
using System;
using DeployFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DeployFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeployFlow.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("AcknowledgedById")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ResourceType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Threshold")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("TenantId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.CostRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasDefaultValue("USD");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("cost_records", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.DatabaseBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("DatabaseInstanceId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StoragePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseInstanceId");

                    b.ToTable("DatabaseBackups");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.DatabaseInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("BackupRetentionDays")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BackupSchedule")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ContainerId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Host")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int?>("Port")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("StorageGb")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("database_instances", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("CommitAuthor")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("CommitMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ImageTag")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsRollback")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<Guid?>("PreviousDeploymentId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.DeploymentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Stream")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("Timestamp");

                    b.ToTable("deployment_logs", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("DnsVerified")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsWildcard")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("RedirectWww")
                        .HasColumnType("NUMBER(1)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("SslEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("SslExpiresAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("SslProvider")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.EnvVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EnvVariables");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.NotificationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("NotificationConfigs");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CronExpression")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("FailedRuns")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<TimeSpan?>("LastDuration")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("SuccessRuns")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("pipelines", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("RunParallel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.ToTable("PipelineStages");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.PipelineStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Command")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)");

                    b.Property<string>("Image")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("PipelineStageId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Timeout")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineStageId");

                    b.ToTable("PipelineSteps");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("AutoDeployEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("BranchDeployEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("BuildCommand")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("DeploymentCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("DockerfilePath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Framework")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("HealthCheckPath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("HealthCheckTimeout")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("InstallCommand")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastDeployedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("LastDeploymentId")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("LastDeploymentStatus")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("OutputDirectory")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Port")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("PreviewDeployEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("RepositoryBranch")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("RootDirectory")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("StartCommand")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.ProjectTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("project_tags", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("ActiveContainers")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Arch")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CpuCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("DiskGb")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("DiskUsagePercent")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("DockerVersion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsSwarmManager")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsSwarmWorker")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("KubernetesEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("MemoryGb")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("MemoryUsagePercent")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Os")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid?>("SshKeyId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("SshPort")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SshUser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("SwarmNodeId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.ServerMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("ActiveContainers")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<long>("DiskTotalBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("DiskUsageBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double>("LoadAverage1m")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MemoryUsageBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("NetworkRxBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("NetworkTxBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Timestamp");

                    b.ToTable("server_metrics", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ContainerId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CpuLimit")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CpuRequest")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("HealthCheckInterval")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("HealthCheckPath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("HealthCheckRetries")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("HealthCheckStartPeriod")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("HealthCheckTimeout")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Image")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("MemoryLimit")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MemoryRequest")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Replicas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tag")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.SshKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("PrivateKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ssh_keys", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MaxDeployments")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MaxProjects")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MaxServers")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("SsoClientId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("SsoClientSecret")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<bool>("SsoEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SsoIssuer")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.DatabaseBackup", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.DatabaseInstance", "DatabaseInstance")
                        .WithMany()
                        .HasForeignKey("DatabaseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseInstance");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Deployment", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Project", "Project")
                        .WithMany("Deployments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.DeploymentLog", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Deployment", "Deployment")
                        .WithMany("Logs")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.EnvVariable", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Project", "Project")
                        .WithMany("EnvVariables")
                        .HasForeignKey("ProjectId");

                    b.HasOne("DeployFlow.Domain.Entities.Service", "Service")
                        .WithMany("EnvVariables")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Project");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Pipeline", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.PipelineStage", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Pipeline", null)
                        .WithMany("Stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.PipelineStep", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.PipelineStage", null)
                        .WithMany("Steps")
                        .HasForeignKey("PipelineStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Project", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Server", null)
                        .WithMany("Projects")
                        .HasForeignKey("ServerId");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Service", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.Project", "Project")
                        .WithMany("Services")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeployFlow.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DeployFlow.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Deployment", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Pipeline", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.PipelineStage", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Project", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("EnvVariables");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Server", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("DeployFlow.Domain.Entities.Service", b =>
                {
                    b.Navigation("EnvVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
